<?php
$pageTitle = 'Diagnostic Reports';
require_once __DIR__ . '/../includes/header.php';
requireLogin();

$sections = $pdo->query("SELECT * FROM sections ORDER BY grade_level, section_name")->fetchAll();

$recentReports = $pdo->query("SELECT dr.*, u.full_name as generated_by_name,
    CONCAT(s.first_name, ' ', s.last_name) as student_name,
    sec.section_name
    FROM diagnostic_reports dr
    LEFT JOIN users u ON dr.generated_by = u.id
    LEFT JOIN students s ON dr.student_id = s.id
    LEFT JOIN sections sec ON dr.section_id = sec.id
    ORDER BY dr.created_at DESC LIMIT 20")->fetchAll();

require_once __DIR__ . '/../includes/sidebar.php';
?>

<!-- Report Types -->
<div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-5 mb-8">
    <a href="<?= BASE_URL ?>reports/individual.php" class="stat-card hover:border-gray-300 cursor-pointer group" style="background:#eff6ff;">
        <div class="w-12 h-12 rounded-lg flex items-center justify-center mb-3 transition-colors" style="background:#dbeafe;">
            <i class="fas fa-user text-lg" style="color:#1d4ed8;"></i>
        </div>
        <h4 class="text-sm font-semibold text-gray-800">Individual Report</h4>
        <p class="text-xs text-gray-500 mt-1">Generate diagnostic report for a single student</p>
    </a>

    <a href="<?= BASE_URL ?>reports/section_report.php" class="stat-card hover:border-gray-300 cursor-pointer group" style="background:#f0fdf4;">
        <div class="w-12 h-12 rounded-lg flex items-center justify-center mb-3 transition-colors" style="background:#dcfce7;">
            <i class="fas fa-users text-lg" style="color:#166534;"></i>
        </div>
        <h4 class="text-sm font-semibold text-gray-800">Section Report</h4>
        <p class="text-xs text-gray-500 mt-1">Generate report for an entire section</p>
    </a>

    <a href="<?= BASE_URL ?>reports/class_performance.php" class="stat-card hover:border-gray-300 cursor-pointer group" style="background:#fffbeb;">
        <div class="w-12 h-12 rounded-lg flex items-center justify-center mb-3 transition-colors" style="background:#fef3c7;">
            <i class="fas fa-chart-bar text-lg" style="color:#92400e;"></i>
        </div>
        <h4 class="text-sm font-semibold text-gray-800">Class Performance</h4>
        <p class="text-xs text-gray-500 mt-1">Summary of class performance across subjects</p>
    </a>

    <a href="<?= BASE_URL ?>competency/index.php" class="stat-card hover:border-gray-300 cursor-pointer group" style="background:#fef2f2;">
        <div class="w-12 h-12 rounded-lg flex items-center justify-center mb-3 transition-colors" style="background:#fee2e2;">
            <i class="fas fa-exclamation-triangle text-lg" style="color:#b91c1c;"></i>
        </div>
        <h4 class="text-sm font-semibold text-gray-800">Competency Report</h4>
        <p class="text-xs text-gray-500 mt-1">Identify weak competencies and at-risk students</p>
    </a>
</div>

<!-- Recent Reports -->
<div class="bg-white border border-gray-200 rounded-xl overflow-hidden">
    <div class="px-6 py-4 border-b border-gray-200">
        <h3 class="text-sm font-semibold text-gray-900">Recent Reports</h3>
    </div>
    <div class="overflow-x-auto">
        <table class="steps-table">
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Type</th>
                    <th>Subject</th>
                    <th>Generated By</th>
                    <th>School Year</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($recentReports as $rpt): ?>
                    <tr>
                        <td class="text-sm"><?= date('M d, Y h:i A', strtotime($rpt['created_at'])) ?></td>
                        <td>
                            <span class="badge badge-blue capitalize"><?= str_replace('_', ' ', $rpt['report_type']) ?></span>
                        </td>
                        <td class="font-medium">
                            <?php if ($rpt['student_name']): ?>
                                <?= sanitize($rpt['student_name']) ?>
                            <?php elseif ($rpt['section_name']): ?>
                                <?= sanitize($rpt['section_name']) ?>
                            <?php else: ?>
                                General
                            <?php endif; ?>
                        </td>
                        <td><?= sanitize($rpt['generated_by_name'] ?? 'System') ?></td>
                        <td><?= sanitize($rpt['school_year']) ?></td>
                    </tr>
                <?php endforeach; ?>
                <?php if (empty($recentReports)): ?>
                    <tr><td colspan="5" class="text-center text-gray-400 py-8">No reports generated yet.</td></tr>
                <?php endif; ?>
            </tbody>
        </table>
    </div>
</div>

<?php require_once __DIR__ . '/../includes/footer.php'; ?>
